apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-pipeline-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/ajagup/ajay-dimitri-next-app-repo
    - name: image-repo
      value: quay.io/ajay_gup/express-sample-app
    - name: app-name
      value: ajay-dimitri-next-app
  pipelineRef:
    name: next-app-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
